version: '3'
services:
  ui:
    image: sf-srms-ui:latest
    stdin_open: true
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - srms
  
  api:
    image: sf-srms-api:latest
    ports:
      - "8006:8006"
    networks:
      - srms

networks:
  srms:
    driver: bridge